### ISSUE TITLE
Add tests to ensure all patched types properly call `_super` in `init`.

### ISSUE THREAD

**Issue by rwjblue** [rwjblue/ember-lifeline#4]
When https://github.com/rwjblue/ember-lifeline/issues/1 is completed we will need to add some unit tests into the consuming application to ensure that users always calls `this._super` in `init` and `willDestroy`.

**Comment by scalvert** [comment]
I think we don't need to worry about this anymore since we lazily allocate, which ensures that properties are created if used. Previously, if you didn't correctly call `_super` and subsequently called `willDestroy` in your class, you would potentially cause an error due to the property not being created/initialized.
